---
- hosts: test
  gather_facts: no
  become: yes
  tasks:
    - name: Creating user2&user3
      user:
        name: '{{ item }}'
        append: yes
        state: present
        createhome: yes
        shell: /bin/bash
      with_items:
        - user2
        - user3

    - name: Creating group
      group:
        name: superusers
        state: present

    - name: Adding users to group
      user:
        name: '{{ item }}'
        groups: superusers
        append: yes
      with_items:
        - user2
        - user3

    - name: Allow superusers to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%superusers'
        line: '%superusers ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'
