---
# tasks file for dnsmasq
- name: Installing dnsmasq
  apt:
    name: dnsmasq
    state: present

- name: Starting dnsmasq
  service:
    name: dnsmasq
    state: started
    enabled: yes

- name: Setting config-file
  copy:
    src: dnsmasq.conf
    dest: /etc/dnsmasq.conf

- name: Restarting dnsmasq
  service:
    name: dnsmasq
    state: restarted
