---
# tasks file for dnsmasq
- name: Installing dnsmasq
  apt:
    name: dnsmasq
    state: present

- name: Starting dnsmasq
  service:
    name: dnsmasq
    state: started
    enabled: yes

- name: Setting configuration
  template:
    src: templates/etc_dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
    validate: 'dnsmasq --test --conf-file=%s'
  notify: restart dnsmasq
